# Makefile
# Glen Wiley <gwiley@rockcastleengineering.com>

rce-bomb.pdf : main.roff overview.roff
	./builddoc

clean:
	rm -f *.bak rce-bomb.roff rce-bomb.ps

clobber: clean
	rm -f rce-bomb.pdf

# Makefile
